# Generated by Django 3.1.12 on 2024-11-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('fthg', models.IntegerField()),
                ('ftag', models.IntegerField()),
                ('ftr', models.CharField(max_length=1)),
                ('winner', models.CharField(max_length=100)),
                ('loser', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'PREMIER_LEAGUE',
            },
        ),
    ]
