# Generated by Django 3.1.12 on 2024-12-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footballApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='away_team',
            new_name='AwayTeam',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='ftag',
            new_name='FTAG',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='fthg',
            new_name='FTHG',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='ftr',
            new_name='FTR',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='home_team',
            new_name='HomeTeam',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='loser',
            new_name='Loser',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='season',
            new_name='Season',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='winner',
            new_name='Winner',
        ),
    ]
